    CREATE TABLE USUARIO (
	ID int,
    FIRST_NAME_USUARIO varchar(255),
    LAST_NAME_USUARIO varchar(255),
	DOCUMENT_USUARIO varchar(255),
	PRIMARY KEY(ID)
	)
	;
	
	CREATE TABLE ENDERECO (
	ID int,
    LOGRADOURO_ENDERECO varchar(255),
    CEP_ENDERECO varchar(255),
	CIDADE_ENDERECO varchar(255),
	USUARIO_ID int,
	PRIMARY KEY(ID)
	)
	;
	
	ALTER TABLE IF EXISTS ENDERECO ADD CONSTRAINT USUARIO_ENDERECO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO;